name: Gradle Build

on:
  pull_request:
  push:
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  gradle-wrapper-validation:
    name: Gradle Wrapper validation
    uses: OmicoDev/gradle-project-initializer-template/.github/workflows/gradle-wrapper-validation.yml@main

  gradle-build:
    name: Gradle Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - gradle-wrapper-validation
    env:
      DEPENDENCY_GRAPH_EXCLUDE_PROJECTS: ':(gradm|initialization|project)'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true
          dependency-graph: generate-and-submit

      - run: ./gradlew build --no-daemon --stacktrace
