name: Gradle Build

on:
  pull_request:
  push:
    branches:
      - 'main'
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: false

jobs:
  gradle-wrapper-validation:
    name: Gradle Wrapper validation
    uses: OmicoDev/gradle-project-initializer-template/.github/workflows/gradle-wrapper-validation.yml@main

  gradle-build:
    name: Gradle Build
    runs-on: ubuntu-latest
    needs: gradle-wrapper-validation
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true

      - run: ./gradlew build --no-daemon --stacktrace

  gradle-submit-dependency-graph:
    name: Gradle Submit Dependency Graph
    uses: OmicoDev/gradle-project-initializer-template/.github/workflows/gradle-submit-dependency-graph.yml@main
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: gradle-build
    permissions:
      contents: write
